import cron from 'node-cron';
import { requestGenerateReport } from './reports.js';
import { SecurityScan } from './security.js';

/**
 * Schedules a recurring task to generate a report for a given URL every minute.
 * 
 * This function uses `node-cron` to schedule a report generation for the specified URL. The report is generated by calling
 * `requestGenerateReport`, which stores the report and processes it through a queue.
 * 
 * @param {string} url - The URL for which to generate the report.
 * @param {Object} store - The LevelDB store instance used to store report requests.
 * @param {Object} queue - The job queue used to process report generation requests.
 * 
 * @returns {void}
 * 
 * @example
 * // Schedule report generation for 'https://example.com' every minute
 * scheduleReportGeneration('https://example.com', store, queue);
 * 
 * @throws {Error} If there is an error while generating the report.
 */
function scheduleReportGeneration(url, store, queue) {
    cron.schedule('* * * * *', async () => {
        try {
            const reportId = await requestGenerateReport(store, queue, url);
            console.log(`Report generated successfully with ID: ${reportId}`);
        } catch (error) {
            console.error('Error generating report:', error);
        }
    });
}

export { scheduleReportGeneration };
